[package]
name = "nexlint"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = { version = "1.0.3", features = ["serde1"] }
debug-ignore = "1.0.1"
determinator = "0.7.0"
guppy = "0.12.3"
hex = "0.4.3"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }
