[package]
name = "nexlint-lints"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.0.3"
cargo_metadata = "0.14.0"
determinator = "0.7.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
anyhow = "1.0.52"
colored-diff = "0.2.2"
guppy = { version = "0.12.3", features = ["summaries"] }
toml = "0.5.8"
log = "0.4.14"
globset = "0.4.6"
regex = "1.4.3"
indexmap = "1.6.2"
nexlint = { path = "../nexlint" }
